- manifest.json
* CiscoMonitor: 5.3.1 -> 5.3.3
* CiscoUCS: 1.9.1 -> 1.9.2
* Microsoft.Windows: 2.2.1 -> 2.3.1
* MySqlMonitor: 3.0.4 -> 3.0.5
* ZenWebTx: 2.9.1 -> 2.9.2
Microsoft.Windows had two entries. One under zenpacks/ and another under
enterprise_zenpacks/. Removed the enterprise_zenpacks/ entry because it
is an open source ZenPack.
> Update tag ref for 5 ZenPacks. Dedupe Windows.

- manifest.json
* EsxTop (Not recommended for use says VMware)
* IRCDMonitor (Rarely used)
* JabberMonitor (Rarely used)
* NNTPMonitor (Rarely used)
* RANCIDIntegrator (Rarely used)
* SugarCRMMonitor (Rarely used)
* VMwareESXMonitor (Deprecated by vSphere)
* XenMonitor (Deprecated by XenServer)
* ZenossVirtualHostMonitor (Deprecated by vSphere & XenServer)
> Remove rarely-used ZenPacks.

- manifest.json
* Fix "Unable to cleanup" warning on first install. (ZEN-16895)
* Fix VRF relationship for FastEthernet interfaces. (ZEN-16896)
> Update CiscoMonitor from 5.3.3 to 5.3.4.

- manifest.json
This PR sets the stage for any future 5.0.x release (e.g. 5.0.7 or higher) to pick up the latest version of all platform zenpacks.
For the 5.0.0-5.0.6 releases, the zenpacks identified in this PR did NOT have a support/5.0.x branch so the manifest had to be manually edited to get each new version. However, I added support/5.0.x branches to all of those zenpacks earlier today, so now the manifest can simply pull the latest versions on those branches.
> Use support/5.0.x branch for all platform zenpacks

- manifest.json
refs for all ZenPack repositories except for UCSCapacity are updated to
either an existing tag we want to use, or a release/* branch to allow us
to be discerning about what further changes can get into the release.
ZenPacks already being tested with their support/5.1.x branch are left
alone.
UCSCapacity is pending some final changes before its release branch will
be created. I'll update its ref later today when it's ready.
> Prepare ZenPack refs for UCS-PM v2 release.

- manifest.json
EnterpriseLinux's functionality is being merged into LinuxMonitor. To
prevent breaking develop build we need to make sure that EnterpriseLinux
and LinuxMonitor are both being built from the same branch.
Fixes ZEN-21606.
> Use master branch of EnterpriseLinux on develop.

- manifest.json
* CiscoMonitor: 5.5.0 -> 5.6.2
* CiscoUCS: 2.2.0 -> 2.3.1
* EMC.base: 1.0.4.1 -> 1.1.0
* NetAppMonitor: 3.1.0 -> 3.3.0
* PropertyMonitor: 1.0.0 -> 1.1.0
* StorageBase: 1.3.0 -> 1.4.1
* WebLogicMonitor: 2.2.2 -> 2.2.3
* WebsphereMonitor: 1.2.1 -> 1.2.2
* ZenSQLTx: 2.6.2 -> 2.6.3
* ZenWebTx: 2.9.2 -> 3.0.0
* vSphere: 3.2.1 -> 3.4.0
* LinuxMonitor: 1.3.0 -> 1.4.1
* Microsoft.Windows: 2.4.8 -> 2.5.7
* MySqlMonitor: 3.0.6 -> 3.0.7
* NtpMonitor: 2.2.1 -> 2.2.2
* WBEM: 1.0.0 -> 1.0.3
* ZenJMX: 3.11.1 -> 3.12.1
> 5.0.x: Bump most Solutions ZenPacks to latest tag.

- manifest.json
* CiscoMonitor: 5.6.0 -> 5.6.2
* CiscoUCSCentral: 1.1.0 -> 1.2.0
* Microsoft.HyperV: 1.2.0 -> 1.2.1
* Microsoft.Windows: 2.5.0 -> 2.5.7
* MySqlMonitor: 3.0.6 -> 3.0.7
* NtpMonitor: 2.2.1 -> 2.2.2
* StorageBase: 1.3.2 -> 1.4.1
* WebLogicMonitor: 2.2.2 -> 2.2.3
* WebsphereMonitor: 1.2.1 -> 1.2.2
* ZenSQLTx: 2.6.2 -> 2.6.3
* ZenWebTx: 2.9.2 -> 3.0.0
> 5.1.x: Bump all Solutions ZenPacks to latest tag.

- manifest.json
This ZenPack is needed because the NetAppMonitor (v3.3) zenpack now has a dependency on the CalculatedPerformance zenpack.
> Add CalculatedPerformance ZenPack to 5.0.x manifest.

- manifest.json
Microsoft.Windows 2.5.8 uncludes the following changes:
* Windows Shell datasource passes severity to parsers. (ZEN-21928)
> Upgrade Windows ZenPack to 2.5.8

- manifest.json
EMC.base 1.1.2 includes the following changes:
* Remove dependency on CalculatedPerformance ZenPack. (ZEN-19707)
* Fix incorrect data device (LUN) impacts. (ZEN-21813)
> Upgrade EMC ZenPack to 1.1.2.

- manifest.json
Changes from 2.5.8 to 2.5.10:
- Fix Windows Team NIC Monitoring/Modeling Failure (ZEN-19588)
- Fix Microsoft Windows Cluster datasources are sending datamaps too
often and bogging down zenhub (ZEN-22345)
https://github.com/zenoss/ZenPacks.zenoss.Microsoft.Windows/compare/2.5.8...2.5.10
> (5.1.x) Update Microsoft.Windows ZenPack: 2.5.8 to 2.5.10

- manifest.json
Changes from 2.3.2 to 2.3.4:
- Fix re-opening of events when UCS deletes them. (ZEN-22420)
- Fix potential Impact modeling performance issue.
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCS/compare/2.3.2...2.3.4
> (5.1.x) Update CiscoUCS ZenPack: 2.3.2 to 2.3.4

- manifest.json
Changes from 5.6.2 to 5.6.3:
- Indicate NX-API for Nexus 9000 in Add Infrastructure Wizard.
(ZEN-21165)
- Associate cefcPowerStatusChange events with Ethernet interfaces.
(ZEN-21726)
https://github.com/zenoss/ZenPacks.zenoss.CiscoMonitor/compare/5.6.2...5.6.3
> (5.1.x) Update CiscoMonitor ZenPack: 5.6.2 to 5.6.3

- manifest.json
This doesn't do much by itself. There'll be a corresponding update to
platform-build to cause NetScaler to be built, packaged, but not
installed by default.
> (develop) Add NetScaler ZenPack to manifest

- manifest.json
This doesn't do much by itself. There'll be a corresponding update to
platform-build to cause NetScaler to be built, package, but not
installed by default.
See 461efb5 for the develop version of this change.
> (5.1.x) Add NetScaler ZenPack to manifest

- manifest.json
Changes from 3.3.0 to 3.3.1:
- Fixes ZEN-22440 (UTF8 monitoring issue)
https://github.com/zenoss/ZenPacks.zenoss.NetAppMonitor/compare/3.3.0...3.3.1
> (5.1.x) Update NetAppMonitor ZenPack: 3.3.0 to 3.3.1

- manifest.json
Changes from 2.0.1 to 2.2.0:
- Fix excessive remote command execution (ZEN-16740)
- IP Service modeling no longer ignoring zIpServiceMapMaxPort
(ZEN-17360)
- Fix incorrect ssCpuIdle alias for multi-core systems (ZEN-17360)
- Fix handling of European date formats (ZEN-19089)
- Fix incorrect template bindings (ZEN-20078)
- Fix incorrect modeling time (ZEN-22127)
- Add/revise custom component icons, fix icon positioning (ZEN-22191,
ZEN-22294)
- Fix missing Impact YAML file (ZEN-22250)
- Fixed missing graph datapoints (ZEN-22259)
https://github.com/zenoss/ZenPacks.zenoss.AixMonitor/compare/2.0.1..2.2.0
> (5.1.x) Update AixMonitor ZenPack: 2.0.1 -> 2.2.0

- manifest.json
Fixing for UCS-PM 2.0.1 are going into the develop branches of these
ZenPacks. QA needs integrated builds to test the fixes.
> (5.1.x) CiscoMonitor, CiscoUCS, HyperV to develop

- manifest.json
Changes from 1.7.3 to 1.7.4:
- Increase default blockingtimeout from 5 to 30 seconds. (ZEN-22632)
- Enable all plugins if blockingtimeout is set to 0. (ZEN-22633)
https://github.com/zenoss/ZenPacks.zenoss.PythonCollector/compare/1.7.3...1.7.4
> (5.1.x) Update PythonCollector ZenPack: 1.7.3 to 1.7.4

- manifest.json
Changes from 1.2.1 to 1.2.2:
- Fix issue caused by bad evaluationThreshold configuration on
predictive thresholds. (ZEN-23328)
https://github.com/zenoss/ZenPacks.zenoss.UCSCapacity/compare/1.2.1...1.2.2
> (5.1.x) Update UCSCapacity ZenPack: 1.2.1 to 1.2.2

- manifest.json
Changes from 1.1.0 to 1.1.1:
- Fix issue caused by evaluationThreshold being string instead of
integer. (ZEN-23328)
https://github.com/zenoss/ZenPacks.zenoss.PredictiveThreshold/compare/1.1.0...1.1.1
> (5.1.x) Update PredictiveThreshold ZenPack: 1.1.0 to 1.1.1

- manifest.json
ZEN-23669 - update NFVI to use CC ZP 1.2.1
> ZEN-23669 - update NFVI to use CC ZP 1.2.1

- manifest.json
Changes from 2.0.0 to 2.0.1:
- Fix invalid event class in filesystem threshold.
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/compare/2.0.0...2.0.1
> (5.1.x) Update LinuxMonitor ZenPack: 2.0.0 to 2.0.1

- manifest.json
Changes from 2.0.1 to 2.0.2:
- Added property to ignore unmounted hard disks
- Improve 1.x to 2.x migration time. (ZEN-24024)
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/compare/2.0.1...2.0.2
> (5.1.x) Update LinuxMonitor ZenPack: 2.0.1 to 2.0.2

- manifest.json
Changes from 2.2.0 to 2.2.1:
- Updated zenpacklib.py to address modeler timeouts from
attribute-indexed components
https://github.com/zenoss/ZenPacks.zenoss.AixMonitor/compare/2.2.0...2.2.1
> (5.1.x) Update AixMonitor ZenPack: 2.2.0 to 2.2.1

- manifest.json
Changes from 2.6.4 to 2.7.0:
- Conversion to ZPL
- Updated F5 MIBs
- Fixed MIB conflict issues for independently loaded MIBs
- Added Event Class Instances for all SNMP notifications including
- correlations
- Integration with Service Impact
- Added Icons for Service Impact/Dynamic View
- Additional monitoring for PowerSupply
- Revised/corrected datapoint types within RRD Templates
- Improved device resource modeling for memory (host vs. TMM) and swap
- Fixed numerous modeler issues
- Improved Zenoss 5.x compatibility
https://github.com/zenoss/ZenPacks.zenoss.BigIpMonitor/compare/2.6.4...2.7.0
> (5.1.x) Update BigIpMonitor ZenPack: 2.6.4 to 2.7.0

- manifest.json
Changes from 2.5.12 to 2.6.1:
- Enabled the use of the Infrastructure -> Windows Services page
- Enabled domain authentication without the need for DNS
- Added ability to dump results from plugins for troubleshooting
- Converted to use zenpacklib
- Document Microsoft Windows Event Log Monitoring Returns Information Events (ZEN-22904)
- Fix zWinRMServerName not resolving properly on remote collector (ZEN-22880)
- Fix WinRM ZP Error about concurrent shells doesn't close when not reoccuring (ZEN-23010)
- Fix Latest version of WinRM pack (2.5.12) causes "AttributeError: in_exclusions" tracebacks (ZEN-23063)
- Fix WinRM Interface modeler does not account for HP NIC naming scheme (ZEN-20762)
- Fix WinRM monitoring does not emit message for expired password (ZEN-23183)
- Fix Windows kinit: …
> (5.1.x) Update Microsoft.Windows ZenPack: 2.5.12 to 2.6.1

- manifest.json
Changes from 2.4.0 to 2.4.3:
- Optimization improvements for UCS Layer2 Linkable components. (ZEN-19856)
- Status map for storageLocalDisk has been updated with JBOD and Global Hot Spare drive states. (ZEN-22829)
- Fix for all CIMC fault events occuring in August 2014. (ZEN-23438)
- Fix for undefined componentType variable. (ZEN-23459)
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCS/compare/2.4.0...2.4.3
> (5.1.x) Update CiscoUCS ZenPack: 2.4.0 to 2.4.3

- manifest.json
Changes from 3.4.0 to 3.4.1:
- Support multiple --query options in vsphere_queryperf tool
- Improved component grid performance with Zenoss 5.1.4+
- Use epoll reactor in zenvsphere to support >1024 descriptors.
- Fix off-by-one in chunk size calculation (ZEN-22805)
- Monitor ESX host preparation for NSX networking (ZEN-21157)
- Remove Dynamic View component from navigation, since it is not fully supported (ZEN-16277)
https://github.com/zenoss/ZenPacks.zenoss.vSphere/compare/3.4.0...3.4.1
> (5.1.x) Update vSphere ZenPack: 3.4.0 to 3.4.1

- manifest.json
Changes from 2.0.2 to 2.0.3:
- Fix migration of Linux devices to new type. (ZEN-24293)
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/compare/2.0.2...2.0.3
> (5.1.x) Update LinuxMonitor ZenPack: 2.0.2 to 2.0.3

- manifest.json
LinuxMonitor 2.0.0 deprecated EnterpriseLinux. So it's no longer
necessary. On top of that, by having EnterpriseLinux 1.4.0 installed
after LinuxMonitor we end up with badly-merged Linux templates.
Refs ZEN-24385.
> (5.1.x) Remove EnterpriseLinux

- manifest.json
Changes from 2.0.3 to 2.0.4:
- Fix "unimplemented" SSH error on 4.2.5 SP709. (ZEN-23392)
https://github.com/zenoss/ZenPacks.zenoss.LinuxMonitor/compare/2.0.3...2.0.4
> (5.1.x) Update LinuxMonitor ZenPack: 2.0.3 to 2.0.4

- manifest.json
Changes from 2.2.1 to 2.2.2:
- Make event class /Status/OSProcess for process monitoring (ZEN-21999)
- Add zCredentialsZProperties: zCommandUsername & zCommandPassword
- Add mem__pct and fs__pct datapoint aliases (ZEN-24619)
https://github.com/zenoss/ZenPacks.zenoss.AixMonitor/compare/2.2.1...2.2.2
> (5.1.x) Update AixMonitor ZenPack: 2.2.1 to 2.2.2

- manifest.json
Changes from 2.0.0 to 2.0.1:
- Add common datapoint aliases. (ZEN-24619)
https://github.com/zenoss/ZenPacks.zenoss.CheckPointMonitor/compare/2.0.0...2.0.1
> (5.1.x) Update CheckPointMonitor ZenPack: 2.0.0 to 2.0.1

- manifest.json
Changes from 5.7.0 to 5.7.2:
- Fix StatCountInUse and StatCountPeak OID's. (ZEN-12336)
- Fix isProjection template copying error. (ZEN-23332)
- Set event class mapping sequences to 1000. (ZEN-23103)
- Fix ciscoEnvMonSuppStatusChangeNotif trap handler. (ZEN-24123)
- Fix ObjectNotFound zones modeling error
- Fix broken "|" eventKey on NX-API events. (ZEN-21247)
- Add common datapoint aliases. (ZEN-24619)
https://github.com/zenoss/ZenPacks.zenoss.CiscoMonitor/compare/5.7.0...5.7.2
> (5.1.x) Update CiscoMonitor ZenPack: 5.7.0 to 5.7.2

- manifest.json
Changes from 2.0.0 to 2.0.1:
- Fix modeling "ValueError" when swap volumes are disabled (ZEN-23286)
- Add common datapoint aliases (ZEN-24619)
https://github.com/zenoss/ZenPacks.zenoss.HpuxMonitor/compare/2.0.0...2.0.1
> (5.1.x) Update HpuxMonitor ZenPack: 2.0.0 to 2.0.1

- manifest.json
Changes from 2.2.0 to 2.2.1:
- Add total memory modeling
- Change free memory threshold from 524288 bytes to 10% of total
- Add common datapoint aliases (ZEN-24619)
https://github.com/zenoss/ZenPacks.zenoss.NetScreenMonitor/compare/2.2.0...2.2.1
> (5.1.x) Update NetScreenMonitor ZenPack: 2.2.0 to 2.2.1

- manifest.json
Changes from 2.4.1 to 2.4.2:
- Fix process monitoring event class and threshold (ZEN-21999)
- Fix for handling of empty zone status output
- Add common datapoint aliases (ZEN-24619)
https://github.com/zenoss/ZenPacks.zenoss.SolarisMonitor/compare/2.4.1...2.4.2
> (5.1.x) Update SolarisMonitor ZenPack: 2.4.1 to 2.4.2

- manifest.json
Changes from 2.6.3 to 2.6.4:
- Fix broken "timeout" field in SQL datasource edit dialog (ZEN-22955)
- Make SQL libraries importable by other ZenPacks (ZEN-23722)
https://github.com/zenoss/ZenPacks.zenoss.ZenSQLTx/compare/2.6.3...2.6.4
> Update ZenSQLTx ZenPack: 2.6.3 to 2.6.4

- manifest.json
If CC is running on a non-standard port, the new CC device will
fail to monitor until you manually edit the property.
On the 'Add Infrastructure' page add field for Port when adding
new CC device.
> ZEN-24142: add zControlCenterPort property in UI when adding CC device

- manifest.json
Changes from 3.3.2 to 3.4.2:
- Add support 9.0(C-Mode) ONTAP API version.
- Add Port component
- Add status monitoring for "vServer" and "Disk Shelf" components
- Fix ZEN-21557 (attribute error during modeling and monitoring)
- Fix ZEN-22440 (UTF8 monitoring issue)
- Fix ZEN-18846 (recursion error on a large number of records)
- Fix issue with negative scale for graphs
- Fix ZEN-21145 (fails to upgrade earlier version)
- Fix performance issue during modeling NFS Client components
- Fix modeling operational status and speed properties for virtual Interface components
https://github.com/zenoss/ZenPacks.zenoss.NetAppMonitor/compare/3.3.2...3.4.2
Fixes ZEN-26328.
> Update NetAppMonitor ZenPack: 3.3.2 to 3.4.2

- manifest.json
Changes from 2.5.2 to 2.5.4:
- Fix collection stall caused by interrupted connectivity. (ZPS-503)
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCS/compare/2.5.2...2.5.4
> Update CiscoUCS ZenPack: 2.5.2 to 2.5.4

- manifest.json
Changes from 2.5.4 to 2.5.5:
- Fix warnings in modeling results. (ZPS-645)
- Fix CIMC "Maximum sessions reached" error. (ZPS-227)
https://github.com/zenoss/ZenPacks.zenoss.CiscoUCS/compare/2.5.4...2.5.5
> Update CiscoUCS ZenPack: 2.5.4 to 2.5.5
